### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Lakshay-Awasthi** [bitnami/bitnami-docker-tensorflow-serving#13]
**Description**
Tensor serving container is giving below error 
tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: /<models_folder_path>; Too many open files

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
You might need to increase the open files limit of your system (`ulimit`). You have here an article on the topic: https://posidev.com/blog/2009/06/04/set-ulimit-parameters-on-ubuntu/

**Comment by Lakshay-Awasthi** [comment]
Thanks @andresbono , One more info will has to be checked the system or inside the docker image.

Regards,
Lakshay

**Comment by andresbono** [comment]
Hi @Lakshay-Awasthi, please check the values in both environments.

This [link](https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit) can also be of your interest.
