### ISSUE TITLE
Version tag does not work

### ISSUE THREAD

**Issue by Krith-man** [bitnami/bitnami-docker-tensorflow-serving#15]
### Name and Version

bitnami/latest

### What steps will reproduce the bug?

Having two versions of my model in the tensorflow_serving_data folder (/1/ and /2/).
Just using the "docker-compose up" and having assigned at .yml file 'version: '1'', will always take the latest version(in my case /2/) I have produced. 

### What is the expected behavior?

The expected behavior would be to specify the version tag at the .yml file and it would work. 

### What do you see instead?

Having two versions of my model in the tensorflow_serving_data folder (/1/ and /2/).
Just using the "docker-compose up" and having assigned at .yml file 'version: '1'', will always take the latest version(in my case /2/) I have produced.

**Comment by carrodher** [comment]
Can you share with us a working example to reproduce the issue? What are the changes performed into the _docker-compose.yaml_?

**Comment by carrodher** [comment]
Can you take a look at [this section](https://github.com/bitnami/bitnami-docker-tensorflow-serving#configuration-file) of the README?

**Comment by Krith-man** [comment]
This section is not helping at all. All it says is about adding a conf file to look at 'bitnami' folder. What does this config file include exactly?
 How is this related to the two configuration files mentioned above?
Is there any working example for adding model_config_file and batching_parameters_file?

**Comment by carrodher** [comment]
That section describes how to pass any custom configuration file to the container, then the process running the TensorFlow will use them, but we don't have expertise about how the application itself can be configured. For information regarding the application itself or customization of the content within the application; we highly recommend checking forums and user guides made available by the project behind the application.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
