### ISSUE TITLE
why not expose the rest port. I think should have --port, --rest_api_port, and rpc....

### ISSUE THREAD

**Issue by NobleYd** [bitnami/bitnami-docker-tensorflow-serving#6]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi,

Thanks for the suggestion. We have created an internal ticket for implementing this feature to our Bitnami TensorFlow Serving container solution.

Unfortunately, we're unable to give any estimation as for when we'll start working on this. Once we do, we will update this ticket.

**Comment by tompizmor** [comment]
Hi @NobleYd, 

This is just a quick note to let you know that the rest api port is now exposed and configurable via the TENSORFLOW_SERVING_REST_API_PORT_NUMBER environment variable.
